Repository ironcore-dev/dpservice-cli, pull requests merged in 2023-12, with the labels that each got.

#30 Update golang dependencies and bump dpservice-go to v0.3.0
  go.mod
  go.sum
Labels: enhancement, size/M

#28 Add and enhance documentation
  README.md
  docs/README.md
  docs/development/README.md
  docs/development/add_new_subcommand.md
  docs/development/install.md
  docs/development/usage.md
Labels: documentation, enhancement, size/L

#34 Add PR template to project
  .github/pull_request_template.md
Labels: documentation, size/XS, chore

#33 Add CODEOWNERS file to project
  .github/release-drafter.yml
  CODEOWNERS
Labels: size/S, chore
